"""A modest hand-curated list of common English words, used as the
default dictionary for the demo and for tests that want "realistic"
fuzzy-matching behavior (e.g. correcting "recieve" to "receive"). Not
meant to be exhaustive -- just varied enough in length and letter
patterns to exercise the trie and BK-tree meaningfully."""

COMMON_WORDS = [
    "a", "about", "above", "across", "act", "action", "add", "after",
    "again", "against", "age", "agree", "air", "all", "almost", "alone",
    "along", "already", "also", "although", "always", "among", "and",
    "animal", "another", "answer", "any", "apple", "area", "arm", "around",
    "arrive", "art", "as", "ask", "at", "attack", "aunt", "autumn",
    "away", "baby", "back", "bad", "bag", "ball", "bank", "base",
    "basket", "be", "beach", "bear", "beautiful", "because", "become",
    "bed", "been", "before", "begin", "behind", "believe", "bell",
    "below", "beside", "best", "better", "between", "big", "bird",
    "black", "blue", "boat", "body", "book", "border", "born", "both",
    "bottle", "bottom", "box", "boy", "branch", "bread", "break",
    "breakfast", "bridge", "bright", "bring", "brother", "brown", "build",
    "burn", "business", "busy", "but", "buy", "by", "cake", "call",
    "camera", "camp", "can", "candle", "capital", "captain", "car",
    "card", "care", "careful", "carry", "case", "castle", "cat", "catch",
    "cause", "cell", "center", "century", "certain", "chair", "chance",
    "change", "character", "charge", "chase", "cheap", "check", "cheese",
    "chicken", "child", "children", "choice", "choose", "circle", "city",
    "class", "clean", "clear", "climb", "clock", "close", "cloth",
    "cloud", "coast", "coat", "coffee", "cold", "collect", "color",
    "come", "comfort", "common", "company", "compare", "complete",
    "condition", "connect", "consider", "contain", "continue", "control",
    "cook", "cool", "corner", "correct", "cost", "cotton", "could",
    "count", "country", "couple", "course", "cover", "create", "cross",
    "crowd", "cry", "culture", "cup", "current", "cut", "dance",
    "danger", "dark", "date", "daughter", "day", "dead", "deal", "dear",
    "death", "decide", "decision", "deep", "degree", "deliver", "demand",
    "describe", "desert", "design", "desk", "detail", "develop",
    "difference", "different", "difficult", "dinner", "direction",
    "discover", "discuss", "distance", "do", "doctor", "dog", "door",
    "double", "down", "dozen", "draw", "dream", "dress", "drink", "drive",
    "drop", "dry", "during", "each", "ear", "early", "earn", "earth",
    "east", "easy", "eat", "edge", "effect", "egg", "eight", "either",
    "electric", "element", "else", "empty", "end", "enemy", "energy",
    "engine", "enjoy", "enough", "enter", "entire", "equal", "escape",
    "even", "evening", "event", "ever", "every", "example", "except",
    "excite", "exercise", "exist", "expect", "experience", "explain",
    "eye", "face", "fact", "factory", "fail", "fair", "fall", "family",
    "famous", "far", "farm", "fast", "father", "fear", "feel", "few",
    "field", "fight", "figure", "fill", "film", "final", "find", "fine",
    "finger", "finish", "fire", "first", "fish", "fit", "five", "fix",
    "flat", "floor", "flow", "flower", "fly", "follow", "food", "foot",
    "for", "force", "foreign", "forest", "forget", "form", "forward",
    "found", "four", "free", "fresh", "friend", "from", "front", "fruit",
    "full", "fun", "future", "game", "garden", "gate", "general",
    "gentle", "get", "gift", "girl", "give", "glass", "go", "gold",
    "good", "government", "grass", "great", "green", "grey", "ground",
    "group", "grow", "guard", "guess", "guest", "guide", "hair", "half",
    "hand", "happen", "happy", "hard", "hat", "have", "he", "head",
    "health", "hear", "heart", "heat", "heavy", "help", "her", "here",
    "hero", "high", "hill", "history", "hit", "hold", "hole", "holiday",
    "home", "hope", "horse", "hospital", "hot", "hour", "house", "how",
    "huge", "human", "hundred", "hungry", "hunt", "hurry", "hurt",
    "husband", "ice", "idea", "if", "image", "imagine", "important",
    "improve", "in", "include", "increase", "indeed", "industry",
    "inside", "instead", "interest", "into", "introduce", "invite",
    "iron", "island", "it", "job", "join", "journey", "joy", "judge",
    "jump", "just", "keep", "key", "kick", "kill", "kind", "king",
    "kitchen", "knee", "knife", "know", "lady", "lake", "land",
    "language", "large", "last", "late", "laugh", "law", "lay", "lead",
    "leaf", "learn", "least", "leave", "left", "leg", "less", "lesson",
    "let", "letter", "level", "library", "lie", "life", "light", "like",
    "line", "lion", "list", "listen", "little", "live", "local", "lock",
    "long", "look", "lose", "loss", "lot", "loud", "love", "low", "lucky",
    "lunch", "machine", "main", "make", "man", "many", "map", "mark",
    "market", "marry", "master", "match", "material", "matter", "may",
    "meal", "mean", "measure", "meat", "medicine", "meet", "member",
    "memory", "mention", "middle", "might", "mile", "milk", "mind",
    "mine", "minute", "mirror", "miss", "mistake", "mix", "moment",
    "money", "month", "moon", "more", "morning", "most", "mother",
    "mountain", "mouse", "mouth", "move", "much", "music", "must", "my",
    "name", "narrow", "nation", "natural", "nature", "near", "neck",
    "need", "neighbor", "neither", "nest", "never", "new", "news",
    "next", "nice", "night", "nine", "no", "noise", "normal", "north",
    "nose", "not", "note", "nothing", "notice", "now", "number", "nurse",
    "object", "ocean", "of", "off", "offer", "office", "often", "oil",
    "old", "on", "once", "one", "onion", "only", "open", "opinion",
    "opposite", "or", "orange", "order", "organize", "other", "our",
    "out", "outside", "over", "own", "page", "pain", "paint", "pair",
    "paper", "parent", "park", "part", "party", "pass", "past", "path",
    "pattern", "pay", "peace", "pen", "pencil", "people", "perfect",
    "perhaps", "period", "person", "phone", "photo", "phrase", "pick",
    "picture", "piece", "pig", "pin", "place", "plan", "plant", "plate",
    "play", "please", "pocket", "point", "police", "policy", "poor",
    "popular", "position", "possible", "post", "pound", "power",
    "practice", "prepare", "present", "president", "pretty", "prevent",
    "price", "pride", "print", "prison", "private", "prize", "probably",
    "problem", "process", "produce", "product", "program", "promise",
    "proper", "protect", "proud", "provide", "public", "pull", "purple",
    "push", "put", "queen", "question", "quick", "quiet", "quite",
    "race", "radio", "rain", "raise", "range", "rate", "rather", "reach",
    "read", "ready", "real", "reason", "receive", "record", "red",
    "reduce", "region", "relate", "remain", "remember", "remove",
    "repeat", "reply", "report", "represent", "request", "require",
    "rest", "result", "return", "rich", "ride", "right", "ring", "rise",
    "river", "road", "rock", "roll", "roof", "room", "root", "rope",
    "rough", "round", "royal", "rule", "run", "rush", "sad", "safe",
    "sail", "salt", "same", "sand", "save", "say", "scale", "scene",
    "school", "science", "score", "sea", "search", "season", "seat",
    "second", "secret", "section", "see", "seed", "seem", "select",
    "sell", "send", "sense", "sentence", "separate", "serious", "serve",
    "service", "set", "settle", "seven", "several", "shadow", "shake",
    "shall", "shape", "share", "sharp", "she", "sheep", "sheet", "shine",
    "ship", "shirt", "shoe", "shoot", "shop", "short", "should",
    "shoulder", "shout", "show", "sick", "side", "sight", "sign",
    "silence", "silver", "similar", "simple", "since", "sing", "single",
    "sister", "sit", "site", "situation", "six", "size", "skill", "skin",
    "sky", "sleep", "slide", "slow", "small", "smell", "smile", "smoke",
    "snow", "so", "social", "soft", "soil", "soldier", "solid", "some",
    "someone", "something", "sometimes", "son", "song", "soon", "sorry",
    "sort", "sound", "south", "space", "speak", "special", "speed",
    "spell", "spend", "spirit", "spoon", "sport", "spread", "spring",
    "square", "stage", "stand", "star", "start", "state", "station",
    "stay", "steal", "step", "still", "stone", "stop", "store", "storm",
    "story", "straight", "strange", "street", "strength", "strong",
    "structure", "student", "study", "stuff", "subject", "succeed",
    "success", "such", "sudden", "sugar", "suggest", "suit", "summer",
    "sun", "supply", "support", "suppose", "sure", "surface", "surprise",
    "surround", "sweet", "swim", "system", "table", "tail", "take",
    "talk", "tall", "taste", "teach", "teacher", "team", "tear",
    "telephone", "television", "tell", "temperature", "ten", "term",
    "test", "than", "thank", "that", "the", "their", "them", "then",
    "there", "these", "they", "thick", "thin", "thing", "think", "third",
    "this", "those", "though", "thought", "thousand", "three", "through",
    "throw", "thus", "ticket", "time", "tiny", "tired", "title", "to",
    "today", "together", "tomorrow", "tonight", "too", "tool", "tooth",
    "top", "total", "touch", "toward", "town", "trade", "traffic",
    "train", "translate", "travel", "treat", "tree", "trip", "trouble",
    "true", "trust", "truth", "try", "turn", "twelve", "twenty", "twice",
    "two", "type", "under", "understand", "unit", "until", "up", "upon",
    "upper", "use", "usual", "valley", "value", "various", "vegetable",
    "very", "victory", "view", "village", "visit", "voice", "wait",
    "wake", "walk", "wall", "want", "war", "warm", "wash", "waste",
    "watch", "water", "wave", "way", "we", "weak", "wear", "weather",
    "wedding", "week", "weigh", "welcome", "well", "west", "wet", "what",
    "wheel", "when", "where", "whether", "which", "while", "white", "who",
    "whole", "why", "wide", "wife", "wild", "will", "win", "wind",
    "window", "wine", "wing", "winter", "wise", "wish", "with", "within",
    "without", "woman", "wonder", "wood", "word", "work", "world",
    "worry", "worth", "would", "write", "wrong", "yard", "year", "yellow",
    "yes", "yesterday", "yet", "you", "young", "your",
]
